Name: FSM
IconPath: fsm.png
SoundPath: fsm.wav
Description: |
    Implémente et test la FSM avec l'éditeur
BrainsPackage: teams.fsm
AgentsBrainClasses:
    WarBase: WarBaseBrainController
    WarExplorer: WarExplorerBrainController
    WarRocketLauncher: WarRocketLauncherBrainController
    WarKamikaze: WarKamikazeBrainController
    WarEngineer: WarEngineerBrainController
    WarTurret: WarTurretBrainController
FromFsmEditor: true