Name: Time To Explode
IconPath: dekat.png
SoundPath: dekat.wav
Description: |
    Equipe de WarKamikaze tr√®s all-in
BrainsPackage: teams.timetoexplode
AgentsBrainClasses:
    WarBase: WarBaseBrainController
    WarExplorer: WarExplorerBrainController
    WarRocketLauncher: WarRocketLauncherBrainController
    WarKamikaze: WarKamikazeBrainController
    WarEngineer: WarEngineerBrainController
    WarTurret: WarTurretBrainController